import { SidebarFormData } from '../interfaces/interfaces';

export const sidebarData: SidebarFormData = [
   {  name: 'Name', type: 'text', placeholder: "What's your fullname? SIDEBAR" },
   {  name: 'Email from sidebar', type: 'email', placeholder: 'We promise not to spam you. SIDEBAR' },
   {  name: 'Password from sidebar', type: 'password', placeholder: 'Make it a good one! SIDEBAR' },
   {  name: 'About', type: 'textarea', placeholder: 'Tell us a little about yourself ... SIDEBAR'  },
   {  name: 'Phone number', type: 'number', placeholder: 'Enter your mobile number... SIDEBAR' },
]

export const formElements: SidebarFormData = [
   {  name: 'Email', type: 'email', placeholder: 'We promise not to spam you.' },
   {  name: 'Password', type: 'password', placeholder: 'Make it a good one!' },
]

// THIS DATA IS NOT USED YET.
export const originalFormElements = [
   {
       "text_align": "left",
       "status": 1,
       "field_width": "12",
       "icon": "bi bi-pin-map",
       "error": "This field cannot be left empty.",
       "hidden": "no",
       "visible_options": [
           "address",
           "city",
           "state",
           "zipcode",
           "country"
       ],
       "is_required": "no",
       "is_static": "no",
       "label": "Address",
       "read_only": "no",
       "placeholder": "Enter address",
       "custom_id": "elm_MdSC34",
       "element_key": "address_164b7a75-d839-4933-8642-3f6f2cf8e9d1",
       "unique_name": "Address",
       "type": "address",
       "name": "Address",
       "sub_elements": [
           {
               "text_align": "left",
               "status": 0,
               "field_width": "12",
               "error": "This field cannot be left empty.",
               "is_required": "no",
               "label": "Address",
               "read_only": "no",
               "placeholder": "Enter address",
               "element_key": "address",
               "unique_name": "Address",
               "type": "text_input",
               "name": "Address",
               "element_uuid": "00000000-0000-0000-0000-000000000000",
               "_id": "32981a1b-cabe-4003-a4e4-c88b8fe1eb64",
               "sub_el_type": "address"
           },
           {
               "text_align": "left",
               "status": 0,
               "field_width": "12",
               "error": "This field cannot be left empty.",
               "is_required": "no",
               "label": "City",
               "read_only": "no",
               "placeholder": "Enter city",
               "element_key": "city",
               "unique_name": "City",
               "type": "text_input",
               "name": "City",
               "element_uuid": "00000000-0000-0000-0000-000000000000",
               "_id": "e9a4684d-33d4-4158-841b-81fbef9e3c23",
               "sub_el_type": "city"
           },
           {
               "text_align": "left",
               "status": 0,
               "field_width": "12",
               "error": "This field cannot be left empty.",
               "is_required": "no",
               "label": "State",
               "read_only": "no",
               "placeholder": "Enter state",
               "element_key": "state",
               "unique_name": "State",
               "type": "text_input",
               "name": "State",
               "element_uuid": "00000000-0000-0000-0000-000000000000",
               "_id": "ff904d21-b8fb-46d6-ad23-50c5151e153b",
               "sub_el_type": "state"
           },
           {
               "text_align": "left",
               "status": 0,
               "field_width": "12",
               "error": "This field cannot be left empty.",
               "is_required": "no",
               "label": "Postal/Zip Code",
               "read_only": "no",
               "placeholder": "Enter postal/zip code",
               "element_key": "zipcode",
               "unique_name": "Postal/Zip Code",
               "type": "text_input",
               "name": "Postal/Zip Code",
               "element_uuid": "00000000-0000-0000-0000-000000000000",
               "_id": "731181d8-cbe5-4045-92c7-0ffccb5aa9a1",
               "sub_el_type": "zipcode"
           },
           {
               "text_align": "left",
               "status": 0,
               "field_width": "12",
               "error": "This field cannot be left empty.",
               "is_required": "no",
               "label": "Country",
               "read_only": "no",
               "placeholder": "Enter country",
               "element_key": "country",
               "unique_name": "Country",
               "type": "text_input",
               "name": "Country",
               "element_uuid": "00000000-0000-0000-0000-000000000000",
               "_id": "6a0f10ec-a622-474d-abfe-ac35dd7239e6",
               "sub_el_type": "country"
           }
       ],
       "created_on": 1727752533,
       "display_order": 1,
       "element_uuid": "164b7a75-d839-4933-8642-3f6f2cf8e9d1"
   },
   {
       "text_align": "left",
       "status": 1,
       "height": "100",
       "field_width": "12",
       "icon": "bi bi-vector-pen",
       "error": "This field cannot be left empty.",
       "hidden": "no",
       "width": "250",
       "is_required": "no",
       "is_static": "no",
       "clear_button_text": "Clear",
       "label": "Signature",
       "sublabel": "Please sign here",
       "custom_id": "elm_60BYtm",
       "element_key": "signature_26efd9c8-43f8-4d89-8428-d669d51f2c28",
       "unique_name": "Signature",
       "type": "signature",
       "name": "Signature",
       "created_on": 1727752523,
       "display_order": 1,
       "element_uuid": "26efd9c8-43f8-4d89-8428-d669d51f2c28"
   },
   {
       "text_align": "left",
       "status": 1,
       "field_width": "12",
       "icon": "bi bi-image",
       "hidden": "no",
       "image_size": "50",
       "rounded": "0",
       "open_in_new_window": "no",
       "align": "left",
       "is_static": "yes",
       "label": "Image",
       "alt_text": "alt-text",
       "custom_id": "elm_whp4Xv",
       "element_key": "image_f509e2af-616c-403a-9129-dcd2da1e5e19",
       "unique_name": "Image",
       "type": "image",
       "name": "Image",
       "created_on": 1727752538,
       "display_order": 3,
       "element_uuid": "f509e2af-616c-403a-9129-dcd2da1e5e19"
   }
]